[package]
name = "macagatchi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arp-toolkit = {version = "0.3.0", features = ["sync"]}
chrono = "0.4.22"
ipnetwork = "0.20.0"
pnet_datalink = "0.31.0"
